# Generated by Django 4.1 on 2024-01-09 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [

        migrations.AlterField(
            model_name='tbl_district',
            name='dist_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Tbl_location',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_name', models.CharField(max_length=25)),
                ('dist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_district')),
            ],
        ),
    ]
