# Generated by Django 4.1 on 2024-01-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_tbl_category_alter_tbl_district_dist_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('cate_name', models.CharField(max_length=25)),
                ('cate_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
