# Generated by Django 4.1 on 2024-01-14 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_tbl_category'),
    ]

    operations = [




    ]
