# Generated by Django 4.1 on 2024-01-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_tbl_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_product',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_price', models.IntegerField(max_length=25)),
                ('pro_stoke', models.IntegerField(max_length=25)),
                ('pro_image', models.ImageField(upload_to='')),
                ('pro_des', models.CharField(max_length=100)),
                ('cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_category')),
            ],
        ),
    ]
