# Generated by Django 4.1 on 2024-01-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='pro_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_product',
            name='pro_stoke',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
