# Generated by Django 4.1 on 2024-01-30 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0006_alter_tbl_product_pro_price_and_more'),
        ('guestapp', '0008_tbl_customer_cust_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_qty', models.BigIntegerField()),
                ('bill_no', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=50)),
                ('cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_customer')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_product')),
            ],
        ),
    ]
