# Generated by Django 4.1 on 2024-01-31 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0008_tbl_customer_cust_gender'),
        ('customerapp', '0002_rename_cart_tbl_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='cust_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_login'),
        ),
    ]
