# Generated by Django 4.1 on 2024-02-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0008_tbl_customer_cust_gender'),
        ('customerapp', '0003_alter_tbl_cart_cust_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Book',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('TotalAmount', models.FloatField()),
                ('billno', models.IntegerField(default=100)),
                ('status', models.CharField(max_length=50)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_login')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Payment',
            fields=[
                ('PaymentId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('TotalAmount', models.FloatField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.tbl_book')),
            ],
        ),
    ]
