# Generated by Django 4.1 on 2024-02-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_tbl_book_tbl_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='del_address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
