# Generated by Django 4.1 on 2024-02-29 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_tbl_payment_del_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_payment',
            name='book',
        ),
        migrations.AddField(
            model_name='tbl_payment',
            name='BookId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customerapp.tbl_book'),
        ),
    ]
