# Generated by Django 4.1 on 2024-02-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0008_rename_billno_tbl_cart_bill_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_payment',
            old_name='BookId',
            new_name='book',
        ),
    ]
