# Generated by Django 4.1 on 2024-01-23 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_product'),
        ('guestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('cust_name', models.CharField(max_length=25)),
                ('cust_address', models.CharField(max_length=50)),
                ('cust_email', models.CharField(max_length=25)),
                ('cust_contact', models.IntegerField(blank=True, null=True)),
                ('cust_pincode', models.IntegerField(blank=True, null=True)),
                ('dist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_district')),
                ('loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_location')),
            ],
        ),
    ]
