# Generated by Django 4.1 on 2024-01-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0002_tbl_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_customer',
            name='dist_id',
        ),
    ]
