# Generated by Django 4.1 on 2024-01-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0003_remove_tbl_customer_dist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_customer',
            name='loginid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_login'),
        ),
    ]
