# Generated by Django 4.1 on 2024-01-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0004_tbl_customer_loginid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tbl_customer',
            name='username',
        ),
    ]
