# Generated by Django 4.1 on 2024-01-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0005_remove_tbl_customer_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customer',
            name='cust_contact',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
