# Generated by Django 4.1 on 2024-01-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0007_alter_tbl_customer_cust_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_customer',
            name='cust_gender',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
